# Project configuration for Hugging Face Inference API automation tests

# Model to use for inference
model1: deepset/roberta-base-squad2
model2: distilbert/distilbert-base-uncased-finetuned-sst-2-english
task1: question_answering
task1_short: QA
task2: sentiment_analysis
task2_short: SA
provider: hf-inference

# Request timeout in seconds
timeout_seconds: 60

# Output directories
artifact_dir: artifacts
report_dir: reports

local_api_url: http://localhost:8000
