# Project configuration for Hugging Face Inference API automation tests

# Model to use for inference
model: deepset/roberta-base-squad2
provider: hf-inference

# Request timeout in seconds
timeout_seconds: 60

# Output directories
artifact_dir: artifacts
report_dir: reports
