version: '3.8'
services:
  # FastAPI app container
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app      # Use app image from Dockerfile 
    container_name: huggingface-inference-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Mount local project code in dev mode
    # volumes:
    #   - .:/app

  # Test container
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test   # Use test image from Dockerfile 
    container_name: huggingface-inference-api-test
    #depends_on:
      #app:
        #condition: service_healthy
    command: >
      bash -c "
        # Start FastAPI in the background
        uvicorn app.main:app --host 0.0.0.0 --port 8000 & 
        # Wait a few seconds for FastAPI to start
        sleep 5
        # Run tests
        pytest --disable-warnings -q \
               --junitxml=reports/junit.xml \
               --html=reports/report.html \
               --self-contained-html
      "
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app   # Mount local project code directly from repo, so no need FastAPI app container/image
      - ./test_data:/app/test_data  # Mount test data separately
    ports:
      - "8000:8000"  # Optional: expose FastAPI port if needed  
