name: CI - Hugging Face Inference API Tests

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run pytest (fast feedback)
        if: github.event_name == 'push'
        run: mkdir -p reports && pytest --maxfail=1 --disable-warnings -q --junitxml=reports/junit.xml --html=reports/report.html --self-contained-html

      - name: Run pytest (full run)
        if: github.event_name == 'pull_request'
        run: mkdir -p reports && pytest --disable-warnings -q --junitxml=reports/junit.xml --html=reports/report.html --self-contained-html

      - name: Upload pytest HTML report 
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html

      - name: Upload junit xml (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: reports/junit.xml

      - name: Upload summary markdown
        uses: actions/upload-artifact@v4
        with:
          name: summary-markdown
          path: |
            reports/summary_qa.md
            reports/summary_sa.md