name: CI - Hugging Face Inference API Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-report:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.2-dind
        options: --privileged --dns 8.8.8.8
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests
        run: |
          docker-compose up --build --exit-code-from test test

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/report.html

      - name: Upload Markdown reports
        uses: actions/upload-artifact@v4
        with:
          name: markdown-reports
          path: |
            reports/summary_qa.md
            reports/summary_sa.md
